"""Load DAT's market-area reference data into Postgres.

Reads the CSVs generated by tools/convert_kma_xlsx.py. Run once after a deploy
that adds the tables, and again whenever DAT reissues the workbook.

    python import_kma.py [data_dir]

The prefix format is re-validated here as well as in the converter. The CSVs are
plain text and a well-meaning trip through Excel silently strips the leading
zero off 005/010/060, in a file that still looks committed and correct.
"""

import argparse
import csv
import logging
import re
import sys
from pathlib import Path
from typing import Dict, List

import db

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

DEFAULT_DATA_DIR = Path(__file__).parent / "data"

US_PREFIX_RE = re.compile(r"^\d{3}$")
CA_PREFIX_RE = re.compile(r"^[A-Z](\d[A-Z]?)?$")

EXPECT_MARKETS = 149
EXPECT_US_PREFIXES = 905
EXPECT_CA_PREFIXES = 227
LEADING_ZERO_CANARY = {"005", "010", "060"}


def read_csv(path: Path) -> List[dict]:
    if not path.exists():
        logger.error("Missing file | path=%s", path)
        sys.exit(1)
    with path.open(encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def clean_prefix(value: str, country: str) -> str:
    """Restore a leading zero Excel may have eaten. Canadian stubs never pad."""
    value = (value or "").strip().upper()
    return value.zfill(3) if country == "US" and value.isdigit() else value


def validate(markets: List[dict], prefixes: List[dict]) -> None:
    problems = []

    if len(markets) != EXPECT_MARKETS:
        problems.append(f"expected {EXPECT_MARKETS} markets, read {len(markets)}")

    us = {p["prefix"] for p in prefixes if p["country"] == "US"}
    ca = {p["prefix"] for p in prefixes if p["country"] == "CA"}

    if len(us) != EXPECT_US_PREFIXES:
        problems.append(f"expected {EXPECT_US_PREFIXES} US prefixes, read {len(us)}")
    if len(ca) != EXPECT_CA_PREFIXES:
        problems.append(f"expected {EXPECT_CA_PREFIXES} CA prefixes, read {len(ca)}")
    if bad := sorted(p for p in us if not US_PREFIX_RE.match(p)):
        problems.append(f"malformed US prefixes: {bad[:10]}")
    if bad := sorted(p for p in ca if not CA_PREFIX_RE.match(p)):
        problems.append(f"malformed CA prefixes: {bad[:10]}")
    if missing := sorted(LEADING_ZERO_CANARY - us):
        problems.append(f"leading zeros missing: {missing} - was the CSV re-saved from Excel?")

    known = {m["market_id"] for m in markets}
    if orphans := {p["market_id"] for p in prefixes} - known:
        problems.append(f"prefixes reference unknown markets: {sorted(orphans)[:5]}")

    if problems:
        for problem in problems:
            logger.error("VALIDATION FAILED | %s", problem)
        sys.exit(1)


def dedupe(records: List[dict], *keys: str) -> List[dict]:
    unique: Dict[tuple, dict] = {tuple(r[k] for k in keys): r for r in records}
    return list(unique.values())


def main() -> None:
    parser = argparse.ArgumentParser(description="Import DAT KMA reference data")
    parser.add_argument("data_dir", nargs="?", default=str(DEFAULT_DATA_DIR))
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    logger.info("Reading reference CSVs | dir=%s", data_dir)

    markets = read_csv(data_dir / "kma_markets.csv")
    prefixes = read_csv(data_dir / "kma_postal_prefixes.csv")
    expanded = read_csv(data_dir / "kma_expanded_prefixes.csv")
    regions = read_csv(data_dir / "kma_regions.csv")

    for row in prefixes:
        row["prefix"] = clean_prefix(row["prefix"], row["country"])
    for row in expanded:
        row["prefix"] = clean_prefix(row["prefix"], "CA" if row["prefix"][:1].isalpha() else "US")
    for row in regions:
        row["prefix"] = clean_prefix(row["prefix"], "CA" if row["prefix"][:1].isalpha() else "US")

    markets = dedupe(markets, "market_id")
    prefixes = dedupe(prefixes, "prefix")
    expanded = dedupe(expanded, "market_id", "prefix")
    regions = dedupe(regions, "region_name", "prefix")

    validate(markets, prefixes)

    # FK order: prefixes and expanded rows reference kma_markets.
    written = {
        "markets": db.upsert_kma_markets(markets),
        "prefixes": db.upsert_kma_postal_prefixes(prefixes),
        "expanded": db.upsert_kma_expanded_prefixes(expanded),
        "regions": db.upsert_kma_regions(regions),
    }

    logger.info(
        "Done | markets=%d prefixes=%d expanded=%d regions=%d",
        written["markets"], written["prefixes"], written["expanded"], written["regions"],
    )


if __name__ == "__main__":
    main()
